### ISSUE TITLE
requirement :  Game Customization Options  - Ensure that customization options are available and applicable to all games offered on the platform.

### ISSUE THREAD

**Issue by Ulysseclem** [cdurdetrouver/transcendance#125]
**Describe the bug**
We don´t offer customization to flappy
Other question : They say all games, does that mean local game too ? 

also go in pair with this : 
Maintain consistency in customization features across all games to provide a
unified user experience

**Comment by cdurdetrouver** [comment]
Create customization such as random map for local game and not for flappy

**Comment by Ulysseclem** [comment]
Ajouté dans la banche map choice
